# Generated by Django 5.2.17 on 2026-09-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('calendar_pattern', models.CharField(choices=[('454', '4-5-4'), ('445', '4-4-5'), ('544', '5-4-4')], default='454', help_text='Retail quarter pattern used for week grouping.', max_length=3)),
                ('boundary_rule', models.CharField(choices=[('first', 'First weekday in month'), ('last', 'Last weekday in month'), ('nearest', 'Nearest weekday to month end')], default='nearest', help_text='How the fiscal year boundary is picked near month end.', max_length=16)),
                ('boundary_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Calendar month that anchors the fiscal year boundary.')),
                ('boundary_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=5, help_text='Weekday used for the boundary rule.')),
            ],
            options={
                'verbose_name': 'fiscal year settings',
                'verbose_name_plural': 'fiscal year settings',
            },
        ),
    ]
