# Generated by Django 5.2.17 on 2026-09-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('provider_name', models.CharField(default='openai-compatible', max_length=64)),
                ('api_base_url', models.URLField(default='https://api.openai.com')),
                ('chat_completions_path', models.CharField(default='/v1/chat/completions', max_length=128)),
                ('api_key_env_var', models.CharField(default='BEARBIZ_AI_API_KEY', max_length=64)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=128)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('max_output_tokens', models.PositiveSmallIntegerField(default=500)),
                ('report_summary_prompt', models.TextField(default='Summarize the weekly sales report for a store manager. Call out notable trends, weak spots, and a practical next action.')),
                ('system_prompt', models.TextField(default="You are Bearbiz's AI report assistant. Write concise, helpful report summaries based only on the supplied report data.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI integration settings',
                'verbose_name_plural': 'AI integration settings',
            },
        ),
    ]
