# Generated by Django 5.2.17 on 2026-09-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiintegrationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiintegrationsettings',
            name='api_base_url',
            field=models.URLField(default='https://api.openai.com/v1'),
        ),
        migrations.AlterField(
            model_name='aiintegrationsettings',
            name='api_key_env_var',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
