# Generated by Django 5.2.17 on 2026-09-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aiintegrationsettings_api_base_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiintegrationsettings',
            name='chat_completions_path',
        ),
    ]
