# Generated by Django 5.2.17 on 2026-09-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_aiintegrationsettings_chat_completions_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyearsettings',
            name='fiscal_year_start_date',
            field=models.DateField(blank=True, help_text='First day of the current fiscal year. The 4-5-4 calendar stays fixed behind the scenes.', null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyearsettings',
            name='calendar_pattern',
            field=models.CharField(choices=[('454', '4-5-4'), ('445', '4-4-5'), ('544', '5-4-4')], default='454', help_text='Fixed to 4-5-4 internally.', max_length=3),
        ),
    ]
