# Generated by Django 5.2.17 on 2026-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtemplate',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
