# Generated by Django 5.2.17 on 2026-09-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysalessummary',
            name='ai_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='weeklysalessummary',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysalessummary',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='weeklysalessummary',
            name='ai_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='weeklysalessummary',
            name='ai_provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='weeklysalessummary',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
