# Generated by Django 5.2.17 on 2026-09-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_bonus_club_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_week', models.BooleanField(default=False)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('monthly_summary', models.JSONField(blank=True, default=dict)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('parse_version', models.PositiveSmallIntegerField(default=1)),
                ('edited_rows', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_summary', to='reports.reportupload')),
            ],
            options={
                'verbose_name': 'payroll summary',
                'verbose_name_plural': 'payroll summaries',
                'ordering': ['-source_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['source_date', '-created_at'], name='reports_pay_source__f3094f_idx')],
            },
        ),
    ]
