# Generated by Django 5.2.17 on 2026-09-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_partiessummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportupload',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('conflict', 'Conflict')], db_index=True, default='pending', max_length=16),
        ),
    ]
