# Generated by Django 5.2.17 on 2026-09-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_payrollweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('fiscal_month', models.PositiveSmallIntegerField()),
                ('fiscal_week', models.PositiveSmallIntegerField()),
                ('held_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('held_previous', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('booked_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('booked_previous', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parties week',
                'verbose_name_plural': 'parties weeks',
                'ordering': ['fiscal_year', 'fiscal_week'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'fiscal_week'), name='unique_parties_week')],
            },
        ),
    ]
