# Generated by Django 5.2.17 on 2026-09-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_partiesweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('fiscal_week', models.PositiveSmallIntegerField()),
                ('store_number', models.CharField(blank=True, max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_name', models.CharField(max_length=255)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('conflict', 'Conflict')], default='pending', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fiscal_year', '-fiscal_week'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'fiscal_week'), name='unique_product_report_fiscal_period')],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('department_rank', models.PositiveSmallIntegerField()),
                ('item_number', models.CharField(max_length=32)),
                ('item_description', models.CharField(max_length=255)),
                ('units_sold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=14)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.productreport')),
            ],
            options={
                'ordering': ['department', 'department_rank', 'item_number'],
            },
        ),
    ]
