# Generated by Django 5.2.17 on 2026-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_missed_opportunity_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentReportImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('fiscal_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fiscal_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=12)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SegmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField()),
                ('fiscal_week', models.PositiveSmallIntegerField()),
                ('day_of_week', models.CharField(max_length=12)),
                ('day_date', models.DateField()),
                ('week_end', models.DateField()),
                ('source_name', models.CharField(max_length=255)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'segment report',
                'verbose_name_plural': 'segment reports',
                'ordering': ['-fiscal_year', '-fiscal_week', 'day_date'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'fiscal_week', 'day_of_week'), name='unique_segment_report_period_day')],
            },
        ),
    ]
